version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9.4-node
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          command: |
            npm ci
      - run:
          command: |
            python3 -m venv env
            source env/bin/activate
      - run:
          command: |
            source env/bin/activate
            pip install pip setuptools --upgrade --ignore-installed
            pip install -r requirements.dev.txt
            pip install --use-feature=in-tree-build .
      - run:
          command: |
            source env/bin/activate
            make test