# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LongformModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_raw', models.TextField()),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'longform_longformmodel',
            },
        ),
        migrations.CreateModel(
            name='LongformModelArgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_raw', models.TextField()),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'longform_longformmodelargs',
            },
        ),
    ]
